





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Fields;
using Sitecore.Data;
using Sitecore.Globalization;


namespace Projects.Models.Glass
{
		public static class Helper
    {
        public static Guid GetTemplateIdFromType<T>()
        {
            Type t = typeof (T);
            SitecoreTypeAttribute sitecoreType =
                (SitecoreTypeAttribute)Attribute.GetCustomAttribute(t, typeof(SitecoreTypeAttribute));
            return new Guid(sitecoreType.TemplateId);
        }
    }
		public interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

        [SitecoreInfo(SitecoreInfoType.Name)]
        string Name { get; set; }

        [SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        IEnumerable<Guid> BaseTemplates { get; }

		[SitecoreInfo(SitecoreInfoType.TemplateName)]
        string TemplateName { get; }

		[SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        string URL { get; }
		
		[SitecoreChildren(IsLazy = true)]
        IEnumerable<GlassBase> Children { get; set; }

		ISitecoreContext Context { get; }
	

   }

	public abstract class GlassBase : IGlassBase{
		
		private readonly ISitecoreContext _context;

	    protected GlassBase(ISitecoreContext context)
        {
            _context = context;
        }

	    [SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

	    [SitecoreInfo(SitecoreInfoType.Name)]
	    public string Name { get; set; }

        [SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
	    public IEnumerable<Guid> BaseTemplates { get; private set; }

	    [SitecoreInfo(SitecoreInfoType.TemplateName)]
        public string TemplateName { get; private set; }

		[SitecoreInfo(SitecoreInfoType.TemplateId)]
        public Guid TemplateId { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        public string URL { get; private set; }

		[SitecoreChildren(IsLazy = true)]
        public virtual IEnumerable<GlassBase> Children { get; set; }

	    public ISitecoreContext Context
	    {
	        get { return _context; }
	    }
	}
}



namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// ISite_Container Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/Site Container</para>	
	/// <para>ID: 07dc0852-0942-4e73-bc8e-5bb2e44e7df8</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_ContainerConstants.TemplateIdString)]
	public partial interface ISite_Container : IGlassBase , global::Projects.Models.Glass.Common.ISiteSectionBase
	{
				}


	public static partial class ISite_ContainerConstants{

			public const string TemplateIdString = "07dc0852-0942-4e73-bc8e-5bb2e44e7df8";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site Container";

					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
			

	}

	
	/// <summary>
	/// Site_Container
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/Site Container</para>	
	/// <para>ID: 07dc0852-0942-4e73-bc8e-5bb2e44e7df8</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_ContainerConstants.TemplateIdString)]
	public partial class Site_Container  : GlassBase, ISite_Container 
	{
	 public Site_Container(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_ContainerConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_ContainerConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_ContainerConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_ContainerConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_ContainerConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_ContainerConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_ContainerConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_ContainerConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISite_ContainerConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
			
	}
}



namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IIsNavigable Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/IsNavigable</para>	
	/// <para>ID: 17ef9369-a57e-49fc-8384-4e2f136796fb</para>	
	/// </summary>
	[SitecoreType(TemplateId=IIsNavigableConstants.TemplateIdString)]
	public partial interface IIsNavigable : IGlassBase 
	{
								/// <summary>
					/// The MenuHoverText field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IIsNavigableConstants.MenuHoverTextFieldName)]
					string MenuHoverText  {get; set;}
			
								/// <summary>
					/// The MenuTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IIsNavigableConstants.MenuTitleFieldName)]
					string MenuTitle  {get; set;}
			
				}


	public static partial class IIsNavigableConstants{

			public const string TemplateIdString = "17ef9369-a57e-49fc-8384-4e2f136796fb";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "IsNavigable";

					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
			

	}

	
	/// <summary>
	/// IsNavigable
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/IsNavigable</para>	
	/// <para>ID: 17ef9369-a57e-49fc-8384-4e2f136796fb</para>	
	/// </summary>
	[SitecoreType(TemplateId=IIsNavigableConstants.TemplateIdString)]
	public partial class IsNavigable  : GlassBase, IIsNavigable 
	{
	 public IsNavigable(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IIsNavigableConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IIsNavigableConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
			
	}
}

namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasTitle Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasTitle</para>	
	/// <para>ID: 2282d64c-30fe-4af8-86bc-783676d11ca3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasTitleConstants.TemplateIdString)]
	public partial interface IHasTitle : IGlassBase 
	{
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasTitleConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IHasTitleConstants{

			public const string TemplateIdString = "2282d64c-30fe-4af8-86bc-783676d11ca3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasTitle";

					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// HasTitle
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasTitle</para>	
	/// <para>ID: 2282d64c-30fe-4af8-86bc-783676d11ca3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasTitleConstants.TemplateIdString)]
	public partial class HasTitle  : GlassBase, IHasTitle 
	{
	 public HasTitle(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasTitleConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}



namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// ISiteHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteHome</para>	
	/// <para>ID: 31987db3-30dc-4bbe-a66d-9853c4aef189</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteHomeConstants.TemplateIdString)]
	public partial interface ISiteHome : IGlassBase , global::Projects.Models.Glass.Common.IPageBase
	{
								/// <summary>
					/// The SiteLogo field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 08a97178-4920-4e6e-9dcc-ab1f861de0ee</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteHomeConstants.SiteLogoFieldName)]
					Image SiteLogo  {get; set;}
			
				}


	public static partial class ISiteHomeConstants{

			public const string TemplateIdString = "31987db3-30dc-4bbe-a66d-9853c4aef189";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SiteHome";

					
			public static readonly ID SiteLogoFieldId = new ID("08a97178-4920-4e6e-9dcc-ab1f861de0ee");
			public const string SiteLogoFieldName = "SiteLogo";
			
					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
			

	}

	
	/// <summary>
	/// SiteHome
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteHome</para>	
	/// <para>ID: 31987db3-30dc-4bbe-a66d-9853c4aef189</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteHomeConstants.TemplateIdString)]
	public partial class SiteHome  : GlassBase, ISiteHome 
	{
	 public SiteHome(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The SiteLogo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 08a97178-4920-4e6e-9dcc-ab1f861de0ee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.SiteLogoFieldName)]
				public virtual Image SiteLogo  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
			
	}
}








namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasDescription Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasDescription</para>	
	/// <para>ID: 8c3baee6-14d2-4d29-aa4f-12bd964da655</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasDescriptionConstants.TemplateIdString)]
	public partial interface IHasDescription : IGlassBase 
	{
								/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasDescriptionConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
				}


	public static partial class IHasDescriptionConstants{

			public const string TemplateIdString = "8c3baee6-14d2-4d29-aa4f-12bd964da655";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasDescription";

					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
			

	}

	
	/// <summary>
	/// HasDescription
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasDescription</para>	
	/// <para>ID: 8c3baee6-14d2-4d29-aa4f-12bd964da655</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasDescriptionConstants.TemplateIdString)]
	public partial class HasDescription  : GlassBase, IHasDescription 
	{
	 public HasDescription(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasDescriptionConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
			
	}
}
namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// IPageBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/PageBase</para>	
	/// <para>ID: 8f46daef-d64a-4acf-9d3a-2e27d21f890c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageBaseConstants.TemplateIdString)]
	public partial interface IPageBase : IGlassBase , global::Projects.Models.Glass.Common.FieldSections.IHasTitle, global::Projects.Models.Glass.Common.FieldSections.IHasDescription, global::Projects.Models.Glass.Common.FieldSections.IHasBreadcrumb, global::Projects.Models.Glass.Common.FieldSections.IHasMetadata, global::Projects.Models.Glass.Common.FieldSections.IHasExternalId, global::Projects.Models.Glass.Common.FieldSections.IHasImage, global::Projects.Models.Glass.Common.FieldSections.IIsNavigable
	{
				}


	public static partial class IPageBaseConstants{

			public const string TemplateIdString = "8f46daef-d64a-4acf-9d3a-2e27d21f890c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "PageBase";

					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
			

	}

	
	/// <summary>
	/// PageBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/PageBase</para>	
	/// <para>ID: 8f46daef-d64a-4acf-9d3a-2e27d21f890c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageBaseConstants.TemplateIdString)]
	public partial class PageBase  : GlassBase, IPageBase 
	{
	 public PageBase(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
			
	}
}
namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasImage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasImage</para>	
	/// <para>ID: 911b120c-006b-4f81-8dab-d325077d58b2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasImageConstants.TemplateIdString)]
	public partial interface IHasImage : IGlassBase 
	{
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasImageConstants.ImageFieldName)]
					Image Image  {get; set;}
			
				}


	public static partial class IHasImageConstants{

			public const string TemplateIdString = "911b120c-006b-4f81-8dab-d325077d58b2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasImage";

					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
			

	}

	
	/// <summary>
	/// HasImage
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasImage</para>	
	/// <para>ID: 911b120c-006b-4f81-8dab-d325077d58b2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasImageConstants.TemplateIdString)]
	public partial class HasImage  : GlassBase, IHasImage 
	{
	 public HasImage(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasImageConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
			
	}
}
namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasBreadcrumb Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasBreadcrumb</para>	
	/// <para>ID: 94c5636f-595c-405e-947d-f240386345de</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasBreadcrumbConstants.TemplateIdString)]
	public partial interface IHasBreadcrumb : IGlassBase 
	{
								/// <summary>
					/// The BreadcrumbTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasBreadcrumbConstants.BreadcrumbTitleFieldName)]
					string BreadcrumbTitle  {get; set;}
			
				}


	public static partial class IHasBreadcrumbConstants{

			public const string TemplateIdString = "94c5636f-595c-405e-947d-f240386345de";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasBreadcrumb";

					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
			

	}

	
	/// <summary>
	/// HasBreadcrumb
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasBreadcrumb</para>	
	/// <para>ID: 94c5636f-595c-405e-947d-f240386345de</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasBreadcrumbConstants.TemplateIdString)]
	public partial class HasBreadcrumb  : GlassBase, IHasBreadcrumb 
	{
	 public HasBreadcrumb(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasBreadcrumbConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
			
	}
}



namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// ISiteSectionBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteSectionBase</para>	
	/// <para>ID: add81fbd-f1f5-45e0-93a1-26a899526ce4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteSectionBaseConstants.TemplateIdString)]
	public partial interface ISiteSectionBase : IGlassBase , global::Projects.Models.Glass.Common.IPageBase
	{
				}


	public static partial class ISiteSectionBaseConstants{

			public const string TemplateIdString = "add81fbd-f1f5-45e0-93a1-26a899526ce4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SiteSectionBase";

					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
			

	}

	
	/// <summary>
	/// SiteSectionBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteSectionBase</para>	
	/// <para>ID: add81fbd-f1f5-45e0-93a1-26a899526ce4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteSectionBaseConstants.TemplateIdString)]
	public partial class SiteSectionBase  : GlassBase, ISiteSectionBase 
	{
	 public SiteSectionBase(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionBaseConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionBaseConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionBaseConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionBaseConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionBaseConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionBaseConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionBaseConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionBaseConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionBaseConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
			
	}
}


namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// ITaxonomyBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/TaxonomyBase</para>	
	/// <para>ID: b6341215-a5a9-4e2b-b2d8-3939f2af7310</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITaxonomyBaseConstants.TemplateIdString)]
	public partial interface ITaxonomyBase : IGlassBase , global::Projects.Models.Glass.Common.FieldSections.IHasExternalId, global::Projects.Models.Glass.Common.FieldSections.IHasTitle
	{
				}


	public static partial class ITaxonomyBaseConstants{

			public const string TemplateIdString = "b6341215-a5a9-4e2b-b2d8-3939f2af7310";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "TaxonomyBase";

					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// TaxonomyBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/TaxonomyBase</para>	
	/// <para>ID: b6341215-a5a9-4e2b-b2d8-3939f2af7310</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITaxonomyBaseConstants.TemplateIdString)]
	public partial class TaxonomyBase  : GlassBase, ITaxonomyBase 
	{
	 public TaxonomyBase(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITaxonomyBaseConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITaxonomyBaseConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}






namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasExternalId Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasExternalId</para>	
	/// <para>ID: dbed97e8-0520-46d4-bfb8-92c2c7f02754</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasExternalIdConstants.TemplateIdString)]
	public partial interface IHasExternalId : IGlassBase 
	{
								/// <summary>
					/// The ExternalId field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasExternalIdConstants.ExternalIdFieldName)]
					string ExternalId  {get; set;}
			
				}


	public static partial class IHasExternalIdConstants{

			public const string TemplateIdString = "dbed97e8-0520-46d4-bfb8-92c2c7f02754";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasExternalId";

					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
			

	}

	
	/// <summary>
	/// HasExternalId
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasExternalId</para>	
	/// <para>ID: dbed97e8-0520-46d4-bfb8-92c2c7f02754</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasExternalIdConstants.TemplateIdString)]
	public partial class HasExternalId  : GlassBase, IHasExternalId 
	{
	 public HasExternalId(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasExternalIdConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
			
	}
}


namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasMetadata Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasMetadata</para>	
	/// <para>ID: fb728d23-dcf8-497c-b28e-1f0d91458a35</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasMetadataConstants.TemplateIdString)]
	public partial interface IHasMetadata : IGlassBase 
	{
								/// <summary>
					/// The Keywords field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasMetadataConstants.KeywordsFieldName)]
					string Keywords  {get; set;}
			
								/// <summary>
					/// The MetaDescription field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasMetadataConstants.MetaDescriptionFieldName)]
					string MetaDescription  {get; set;}
			
				}


	public static partial class IHasMetadataConstants{

			public const string TemplateIdString = "fb728d23-dcf8-497c-b28e-1f0d91458a35";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasMetadata";

					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
			

	}

	
	/// <summary>
	/// HasMetadata
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasMetadata</para>	
	/// <para>ID: fb728d23-dcf8-497c-b28e-1f0d91458a35</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasMetadataConstants.TemplateIdString)]
	public partial class HasMetadata  : GlassBase, IHasMetadata 
	{
	 public HasMetadata(ISitecoreContext context) : base(context)
	    {
	    }
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasMetadataConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasMetadataConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
			
	}
}
