





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Fields;
using Sitecore.Data;
using Sitecore.Globalization;
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Converters;


namespace Projects.Models.Glass
{
			public static class Helper
    {
        public static Guid GetTemplateIdFromType<T>()
        {
            Type t = typeof (T);
            SitecoreTypeAttribute sitecoreType =
                (SitecoreTypeAttribute)Attribute.GetCustomAttribute(t, typeof(SitecoreTypeAttribute));
            return new Guid(sitecoreType.TemplateId);
        }
    }
		public interface IGlassBase{
		
		[SitecoreId]
		[TypeConverter(typeof(IndexFieldGuidValueConverter)), IndexField(BuiltinFields.Group)]
		Guid Id{ get; set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        [IndexField(BuiltinFields.Language), TypeConverter(typeof(IndexFieldLanguageValueConverter))]
        Language Language{ get; set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; set; }

	    [SitecoreInfo(SitecoreInfoType.Name)]
        [IndexField(BuiltinFields.Name)]
	    string Name { get; set; }

        [SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        [IndexField(SearchIndexField.AllTemplates), TypeConverter(typeof(IndexFieldEnumerableConverter))]
	    IEnumerable<Guid> BaseTemplates { get; set; }

        [IndexField(SearchIndexField.Ancestors), TypeConverter(typeof(IndexFieldEnumerableConverter))]
        IEnumerable<Guid> Ancestors { get; set; }

	    [SitecoreInfo(SitecoreInfoType.TemplateName)]
        [IndexField(BuiltinFields.TemplateName)]
        string TemplateName { get; set; }

		[SitecoreInfo(SitecoreInfoType.TemplateId)]
        [TypeConverter(typeof(IndexFieldGuidValueConverter)), IndexField(BuiltinFields.Template)]
        Guid TemplateId { get; set; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; }

		[SitecoreChildren(IsLazy = true)]
        IEnumerable<IGlassBase> Children { get; }

        [SitecoreParent]
	    IGlassBase Parent { get; set; }

		ISitecoreContext Context { get; }

		    T GetParent<T>() where T : class, IGlassBase;
		    bool HasChildren<T>() where T : class, IGlassBase;
		    IEnumerable<T> GetChildren<T>() where T : class, IGlassBase;
		}

	public abstract class GlassBase : IGlassBase{
		
		private readonly ISitecoreContext _context;

	    public GlassBase()
        {
            _context = new SitecoreContext();
        }

	    public GlassBase(ISitecoreContext context)
        {
            _context = context;
        }

	    [SitecoreId]
		[TypeConverter(typeof(IndexFieldGuidValueConverter)), IndexField(BuiltinFields.Group)]
		public virtual Guid Id{ get; set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        [IndexField(BuiltinFields.Language), TypeConverter(typeof(IndexFieldLanguageValueConverter))]
        public virtual Language Language{ get; set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
		[IgnoreIndexField]
        public virtual int Version { get; set; }

	    [SitecoreInfo(SitecoreInfoType.Name)]
        [IndexField(BuiltinFields.Name)]
	    public string Name { get; set; }

        [SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        [IndexField(BuiltinFields.AllTemplates), TypeConverter(typeof(IndexFieldEnumerableConverter))]
	    public IEnumerable<Guid> BaseTemplates { get; set; }

        [IndexField(SearchIndexField.Ancestors), TypeConverter(typeof(IndexFieldEnumerableConverter))]
	    public IEnumerable<Guid> Ancestors { get; set; }

	    [SitecoreInfo(SitecoreInfoType.TemplateName)]
        [IndexField(BuiltinFields.TemplateName)]
        public string TemplateName { get; set; }

		[SitecoreInfo(SitecoreInfoType.TemplateId)]
        [TypeConverter(typeof(IndexFieldGuidValueConverter)), IndexField(BuiltinFields.Template)]
        public Guid TemplateId { get; set; }

        [SitecoreInfo(SitecoreInfoType.Url)]
		[IgnoreIndexField]
        public string Url { get; private set; }

		[SitecoreChildren(IsLazy = true)]
		[IgnoreIndexField]
        public virtual IEnumerable<IGlassBase> Children { get; set; }

        [SitecoreParent]
		[IgnoreIndexField]
	    public IGlassBase Parent { get; set; }

	    public ISitecoreContext Context
	    {
	        get { return _context; }
	    }

	    public T GetParent<T>() where T : class, IGlassBase
	    {
	        T parent = Context.GetItem<T>(Parent.Id);
	        return parent;
	    }

	    public bool HasChildren<T>() where T : class, IGlassBase
	    {
            Guid templateId = Helper.GetTemplateIdFromType<T>();
	        return Children.Any(item => item.BaseTemplates.Contains(templateId));
	    }

        public IEnumerable<T> GetChildren<T>() where T : class, IGlassBase
        {
            Guid templateId = Helper.GetTemplateIdFromType<T>();
            var items = new List<T>();
            if (Children != null)
            {
                items.AddRange(
                    Children.Where(item => item.TemplateId.Equals(templateId) 
										|| item.BaseTemplates.Contains(templateId))
                        .Select(item => Context.GetItem<T>(item.Id)));
            }
               
            return items;
        }
	}
}


namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// ISiteContainer Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteContainer</para>	
	/// <para>ID: 07dc0852-0942-4e73-bc8e-5bb2e44e7df8</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteContainerConstants.TemplateIdString)]
	public partial interface ISiteContainer : IGlassBase , global::Projects.Models.Glass.Common.ISiteSection
	{
				}


	public static partial class ISiteContainerConstants{

			public const string TemplateIdString = "07dc0852-0942-4e73-bc8e-5bb2e44e7df8";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SiteContainer";

					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
					
			public static readonly ID CssClassNameFieldId = new ID("b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3");
			public const string CssClassNameFieldName = "CssClassName";
			
					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
					
			public static readonly ID ShowInMenuFieldId = new ID("64be5630-d2a8-42f4-a127-dd901ee32f6b");
			public const string ShowInMenuFieldName = "ShowInMenu";
			
			

	}

	
	/// <summary>
	/// SiteContainer
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteContainer</para>	
	/// <para>ID: 07dc0852-0942-4e73-bc8e-5bb2e44e7df8</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteContainerConstants.TemplateIdString)]
	public partial class SiteContainer  : GlassBase, ISiteContainer 
	{
	 public SiteContainer(ISitecoreContext context) : base(context)
	    {
	    }

		public SiteContainer() : base()
	    {
	    }
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
						/// <summary>
				/// The CssClassName field.
				/// <para>This will be the Font Awesome Icon classes that will represent the Icons in the breadcrumb</para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.CssClassNameFieldName)]
				public virtual string CssClassName  {get; set;}
					
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
						/// <summary>
				/// The ShowInMenu field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 64be5630-d2a8-42f4-a127-dd901ee32f6b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteContainerConstants.ShowInMenuFieldName)]
				public virtual bool ShowInMenu  {get; set;}
					
			
	}
}



namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IIsNavigable Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/IsNavigable</para>	
	/// <para>ID: 17ef9369-a57e-49fc-8384-4e2f136796fb</para>	
	/// </summary>
	[SitecoreType(TemplateId=IIsNavigableConstants.TemplateIdString)]
	public partial interface IIsNavigable : IGlassBase 
	{
								/// <summary>
					/// The MenuHoverText field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IIsNavigableConstants.MenuHoverTextFieldName)]
					string MenuHoverText  {get; set;}
			
								/// <summary>
					/// The MenuTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IIsNavigableConstants.MenuTitleFieldName)]
					string MenuTitle  {get; set;}
			
								/// <summary>
					/// The ShowInMenu field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 64be5630-d2a8-42f4-a127-dd901ee32f6b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IIsNavigableConstants.ShowInMenuFieldName)]
					bool ShowInMenu  {get; set;}
			
				}


	public static partial class IIsNavigableConstants{

			public const string TemplateIdString = "17ef9369-a57e-49fc-8384-4e2f136796fb";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "IsNavigable";

					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
					
			public static readonly ID ShowInMenuFieldId = new ID("64be5630-d2a8-42f4-a127-dd901ee32f6b");
			public const string ShowInMenuFieldName = "ShowInMenu";
			
			

	}

	
	/// <summary>
	/// IsNavigable
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/IsNavigable</para>	
	/// <para>ID: 17ef9369-a57e-49fc-8384-4e2f136796fb</para>	
	/// </summary>
	[SitecoreType(TemplateId=IIsNavigableConstants.TemplateIdString)]
	public partial class IsNavigable  : GlassBase, IIsNavigable 
	{
	 public IsNavigable(ISitecoreContext context) : base(context)
	    {
	    }

		public IsNavigable() : base()
	    {
	    }
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IIsNavigableConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IIsNavigableConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
						/// <summary>
				/// The ShowInMenu field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 64be5630-d2a8-42f4-a127-dd901ee32f6b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IIsNavigableConstants.ShowInMenuFieldName)]
				public virtual bool ShowInMenu  {get; set;}
					
			
	}
}

namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasTitle Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasTitle</para>	
	/// <para>ID: 2282d64c-30fe-4af8-86bc-783676d11ca3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasTitleConstants.TemplateIdString)]
	public partial interface IHasTitle : IGlassBase 
	{
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasTitleConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IHasTitleConstants{

			public const string TemplateIdString = "2282d64c-30fe-4af8-86bc-783676d11ca3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasTitle";

					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// HasTitle
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasTitle</para>	
	/// <para>ID: 2282d64c-30fe-4af8-86bc-783676d11ca3</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasTitleConstants.TemplateIdString)]
	public partial class HasTitle  : GlassBase, IHasTitle 
	{
	 public HasTitle(ISitecoreContext context) : base(context)
	    {
	    }

		public HasTitle() : base()
	    {
	    }
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasTitleConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}



namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// ISiteHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteHome</para>	
	/// <para>ID: 31987db3-30dc-4bbe-a66d-9853c4aef189</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteHomeConstants.TemplateIdString)]
	public partial interface ISiteHome : IGlassBase , global::Projects.Models.Glass.Common.IPageBase
	{
				}


	public static partial class ISiteHomeConstants{

			public const string TemplateIdString = "31987db3-30dc-4bbe-a66d-9853c4aef189";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SiteHome";

					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
					
			public static readonly ID CssClassNameFieldId = new ID("b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3");
			public const string CssClassNameFieldName = "CssClassName";
			
					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
					
			public static readonly ID ShowInMenuFieldId = new ID("64be5630-d2a8-42f4-a127-dd901ee32f6b");
			public const string ShowInMenuFieldName = "ShowInMenu";
			
			

	}

	
	/// <summary>
	/// SiteHome
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteHome</para>	
	/// <para>ID: 31987db3-30dc-4bbe-a66d-9853c4aef189</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteHomeConstants.TemplateIdString)]
	public partial class SiteHome  : GlassBase, ISiteHome 
	{
	 public SiteHome(ISitecoreContext context) : base(context)
	    {
	    }

		public SiteHome() : base()
	    {
	    }
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
						/// <summary>
				/// The CssClassName field.
				/// <para>This will be the Font Awesome Icon classes that will represent the Icons in the breadcrumb</para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.CssClassNameFieldName)]
				public virtual string CssClassName  {get; set;}
					
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
						/// <summary>
				/// The ShowInMenu field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 64be5630-d2a8-42f4-a127-dd901ee32f6b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHomeConstants.ShowInMenuFieldName)]
				public virtual bool ShowInMenu  {get; set;}
					
			
	}
}

namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasLinkToItem Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasLinkToItem</para>	
	/// <para>ID: 3a6d9f1b-de92-4156-84a7-445c72d68699</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasLinkToItemConstants.TemplateIdString)]
	public partial interface IHasLinkToItem : IGlassBase 
	{
								/// <summary>
					/// The LinkToItem field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 6af0a270-2f22-4791-bdd4-2e90cd441364</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasLinkToItemConstants.LinkToItemFieldName)]
					Link LinkToItem  {get; set;}
			
				}


	public static partial class IHasLinkToItemConstants{

			public const string TemplateIdString = "3a6d9f1b-de92-4156-84a7-445c72d68699";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasLinkToItem";

					
			public static readonly ID LinkToItemFieldId = new ID("6af0a270-2f22-4791-bdd4-2e90cd441364");
			public const string LinkToItemFieldName = "LinkToItem";
			
			

	}

	
	/// <summary>
	/// HasLinkToItem
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasLinkToItem</para>	
	/// <para>ID: 3a6d9f1b-de92-4156-84a7-445c72d68699</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasLinkToItemConstants.TemplateIdString)]
	public partial class HasLinkToItem  : GlassBase, IHasLinkToItem 
	{
	 public HasLinkToItem(ISitecoreContext context) : base(context)
	    {
	    }

		public HasLinkToItem() : base()
	    {
	    }
						/// <summary>
				/// The LinkToItem field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 6af0a270-2f22-4791-bdd4-2e90cd441364</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasLinkToItemConstants.LinkToItemFieldName)]
				public virtual Link LinkToItem  {get; set;}
					
			
	}
}



namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// IContent_Section Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/Content Section</para>	
	/// <para>ID: 47618e20-b728-41fd-a065-392802d1ba49</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContent_SectionConstants.TemplateIdString)]
	public partial interface IContent_Section : IGlassBase 
	{
				}


	public static partial class IContent_SectionConstants{

			public const string TemplateIdString = "47618e20-b728-41fd-a065-392802d1ba49";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Content Section";

			

	}

	
	/// <summary>
	/// Content_Section
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/Content Section</para>	
	/// <para>ID: 47618e20-b728-41fd-a065-392802d1ba49</para>	
	/// </summary>
	[SitecoreType(TemplateId=IContent_SectionConstants.TemplateIdString)]
	public partial class Content_Section  : GlassBase, IContent_Section 
	{
	 public Content_Section(ISitecoreContext context) : base(context)
	    {
	    }

		public Content_Section() : base()
	    {
	    }
			
	}
}








namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasDescription Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasDescription</para>	
	/// <para>ID: 8c3baee6-14d2-4d29-aa4f-12bd964da655</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasDescriptionConstants.TemplateIdString)]
	public partial interface IHasDescription : IGlassBase 
	{
								/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasDescriptionConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
				}


	public static partial class IHasDescriptionConstants{

			public const string TemplateIdString = "8c3baee6-14d2-4d29-aa4f-12bd964da655";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasDescription";

					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
			

	}

	
	/// <summary>
	/// HasDescription
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasDescription</para>	
	/// <para>ID: 8c3baee6-14d2-4d29-aa4f-12bd964da655</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasDescriptionConstants.TemplateIdString)]
	public partial class HasDescription  : GlassBase, IHasDescription 
	{
	 public HasDescription(ISitecoreContext context) : base(context)
	    {
	    }

		public HasDescription() : base()
	    {
	    }
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasDescriptionConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
			
	}
}

namespace Projects.Models.Glass.Common.Components
{


 	/// <summary>
	/// ICarousel Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/Components/Carousel</para>	
	/// <para>ID: 8cc6e1ff-d1c9-46ee-9f55-a58dadb03e84</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselConstants.TemplateIdString)]
	public partial interface ICarousel : IGlassBase 
	{
				}


	public static partial class ICarouselConstants{

			public const string TemplateIdString = "8cc6e1ff-d1c9-46ee-9f55-a58dadb03e84";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Carousel";

			

	}

	
	/// <summary>
	/// Carousel
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/Components/Carousel</para>	
	/// <para>ID: 8cc6e1ff-d1c9-46ee-9f55-a58dadb03e84</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselConstants.TemplateIdString)]
	public partial class Carousel  : GlassBase, ICarousel 
	{
	 public Carousel(ISitecoreContext context) : base(context)
	    {
	    }

		public Carousel() : base()
	    {
	    }
			
	}
}

namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// IPageBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/PageBase</para>	
	/// <para>ID: 8f46daef-d64a-4acf-9d3a-2e27d21f890c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageBaseConstants.TemplateIdString)]
	public partial interface IPageBase : IGlassBase , global::Projects.Models.Glass.Common.FieldSections.IHasTitle, global::Projects.Models.Glass.Common.FieldSections.IHasDescription, global::Projects.Models.Glass.Common.FieldSections.IHasBreadcrumb, global::Projects.Models.Glass.Common.FieldSections.IHasMetadata, global::Projects.Models.Glass.Common.FieldSections.IHasExternalId, global::Projects.Models.Glass.Common.FieldSections.IHasImage, global::Projects.Models.Glass.Common.FieldSections.IIsNavigable
	{
				}


	public static partial class IPageBaseConstants{

			public const string TemplateIdString = "8f46daef-d64a-4acf-9d3a-2e27d21f890c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "PageBase";

					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
					
			public static readonly ID CssClassNameFieldId = new ID("b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3");
			public const string CssClassNameFieldName = "CssClassName";
			
					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
					
			public static readonly ID ShowInMenuFieldId = new ID("64be5630-d2a8-42f4-a127-dd901ee32f6b");
			public const string ShowInMenuFieldName = "ShowInMenu";
			
			

	}

	
	/// <summary>
	/// PageBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/PageBase</para>	
	/// <para>ID: 8f46daef-d64a-4acf-9d3a-2e27d21f890c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageBaseConstants.TemplateIdString)]
	public partial class PageBase  : GlassBase, IPageBase 
	{
	 public PageBase(ISitecoreContext context) : base(context)
	    {
	    }

		public PageBase() : base()
	    {
	    }
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
						/// <summary>
				/// The CssClassName field.
				/// <para>This will be the Font Awesome Icon classes that will represent the Icons in the breadcrumb</para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.CssClassNameFieldName)]
				public virtual string CssClassName  {get; set;}
					
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
						/// <summary>
				/// The ShowInMenu field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 64be5630-d2a8-42f4-a127-dd901ee32f6b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.ShowInMenuFieldName)]
				public virtual bool ShowInMenu  {get; set;}
					
			
	}
}
namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasImage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasImage</para>	
	/// <para>ID: 911b120c-006b-4f81-8dab-d325077d58b2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasImageConstants.TemplateIdString)]
	public partial interface IHasImage : IGlassBase 
	{
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasImageConstants.ImageFieldName)]
					Image Image  {get; set;}
			
				}


	public static partial class IHasImageConstants{

			public const string TemplateIdString = "911b120c-006b-4f81-8dab-d325077d58b2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasImage";

					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
			

	}

	
	/// <summary>
	/// HasImage
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasImage</para>	
	/// <para>ID: 911b120c-006b-4f81-8dab-d325077d58b2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasImageConstants.TemplateIdString)]
	public partial class HasImage  : GlassBase, IHasImage 
	{
	 public HasImage(ISitecoreContext context) : base(context)
	    {
	    }

		public HasImage() : base()
	    {
	    }
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasImageConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
			
	}
}
namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasBreadcrumb Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasBreadcrumb</para>	
	/// <para>ID: 94c5636f-595c-405e-947d-f240386345de</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasBreadcrumbConstants.TemplateIdString)]
	public partial interface IHasBreadcrumb : IGlassBase 
	{
								/// <summary>
					/// The BreadcrumbTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasBreadcrumbConstants.BreadcrumbTitleFieldName)]
					string BreadcrumbTitle  {get; set;}
			
								/// <summary>
					/// The CssClassName field.
					/// <para>This will be the Font Awesome Icon classes that will represent the Icons in the breadcrumb</para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasBreadcrumbConstants.CssClassNameFieldName)]
					string CssClassName  {get; set;}
			
				}


	public static partial class IHasBreadcrumbConstants{

			public const string TemplateIdString = "94c5636f-595c-405e-947d-f240386345de";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasBreadcrumb";

					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
					
			public static readonly ID CssClassNameFieldId = new ID("b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3");
			public const string CssClassNameFieldName = "CssClassName";
			
			

	}

	
	/// <summary>
	/// HasBreadcrumb
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasBreadcrumb</para>	
	/// <para>ID: 94c5636f-595c-405e-947d-f240386345de</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasBreadcrumbConstants.TemplateIdString)]
	public partial class HasBreadcrumb  : GlassBase, IHasBreadcrumb 
	{
	 public HasBreadcrumb(ISitecoreContext context) : base(context)
	    {
	    }

		public HasBreadcrumb() : base()
	    {
	    }
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasBreadcrumbConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
						/// <summary>
				/// The CssClassName field.
				/// <para>This will be the Font Awesome Icon classes that will represent the Icons in the breadcrumb</para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasBreadcrumbConstants.CssClassNameFieldName)]
				public virtual string CssClassName  {get; set;}
					
			
	}
}


namespace Projects.Models.Glass.Common.Components
{


 	/// <summary>
	/// ISlide Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/Components/Slide</para>	
	/// <para>ID: 9f24a886-a36d-4c27-8f9a-f844bf34f710</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISlideConstants.TemplateIdString)]
	public partial interface ISlide : IGlassBase , global::Projects.Models.Glass.Common.FieldSections.IHasImage, global::Projects.Models.Glass.Common.FieldSections.IHasTitle, global::Projects.Models.Glass.Common.FieldSections.IHasDescription, global::Projects.Models.Glass.Common.FieldSections.IHasLinkToItem
	{
				}


	public static partial class ISlideConstants{

			public const string TemplateIdString = "9f24a886-a36d-4c27-8f9a-f844bf34f710";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Slide";

					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID LinkToItemFieldId = new ID("6af0a270-2f22-4791-bdd4-2e90cd441364");
			public const string LinkToItemFieldName = "LinkToItem";
			
			

	}

	
	/// <summary>
	/// Slide
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/Components/Slide</para>	
	/// <para>ID: 9f24a886-a36d-4c27-8f9a-f844bf34f710</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISlideConstants.TemplateIdString)]
	public partial class Slide  : GlassBase, ISlide 
	{
	 public Slide(ISitecoreContext context) : base(context)
	    {
	    }

		public Slide() : base()
	    {
	    }
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISlideConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISlideConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISlideConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The LinkToItem field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 6af0a270-2f22-4791-bdd4-2e90cd441364</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISlideConstants.LinkToItemFieldName)]
				public virtual Link LinkToItem  {get; set;}
					
			
	}
}
namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// IStandardText Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/StandardText</para>	
	/// <para>ID: a3f7e359-81de-480b-85a3-7e7d00ab7be0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IStandardTextConstants.TemplateIdString)]
	public partial interface IStandardText : IGlassBase 
	{
								/// <summary>
					/// The Comment field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: cdba96fd-71df-483e-8773-92e32d0b2d85</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IStandardTextConstants.CommentFieldName)]
					string Comment  {get; set;}
			
								/// <summary>
					/// The Text field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 8c50c2bf-2b08-4be1-a95a-8fc151e849c5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IStandardTextConstants.TextFieldName)]
					string Text  {get; set;}
			
				}


	public static partial class IStandardTextConstants{

			public const string TemplateIdString = "a3f7e359-81de-480b-85a3-7e7d00ab7be0";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "StandardText";

					
			public static readonly ID CommentFieldId = new ID("cdba96fd-71df-483e-8773-92e32d0b2d85");
			public const string CommentFieldName = "Comment";
			
					
			public static readonly ID TextFieldId = new ID("8c50c2bf-2b08-4be1-a95a-8fc151e849c5");
			public const string TextFieldName = "Text";
			
			

	}

	
	/// <summary>
	/// StandardText
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/StandardText</para>	
	/// <para>ID: a3f7e359-81de-480b-85a3-7e7d00ab7be0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IStandardTextConstants.TemplateIdString)]
	public partial class StandardText  : GlassBase, IStandardText 
	{
	 public StandardText(ISitecoreContext context) : base(context)
	    {
	    }

		public StandardText() : base()
	    {
	    }
						/// <summary>
				/// The Comment field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: cdba96fd-71df-483e-8773-92e32d0b2d85</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IStandardTextConstants.CommentFieldName)]
				public virtual string Comment  {get; set;}
					
						/// <summary>
				/// The Text field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 8c50c2bf-2b08-4be1-a95a-8fc151e849c5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IStandardTextConstants.TextFieldName)]
				public virtual string Text  {get; set;}
					
			
	}
}

namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// ISiteSection Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteSection</para>	
	/// <para>ID: add81fbd-f1f5-45e0-93a1-26a899526ce4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteSectionConstants.TemplateIdString)]
	public partial interface ISiteSection : IGlassBase , global::Projects.Models.Glass.Common.IPageBase
	{
				}


	public static partial class ISiteSectionConstants{

			public const string TemplateIdString = "add81fbd-f1f5-45e0-93a1-26a899526ce4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SiteSection";

					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID DescriptionFieldId = new ID("aca2a76a-21f1-4798-9b69-c87764e9ceee");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID BreadcrumbTitleFieldId = new ID("f5de556a-3c9c-4b42-94f3-3ac3a30fa788");
			public const string BreadcrumbTitleFieldName = "BreadcrumbTitle";
			
					
			public static readonly ID CssClassNameFieldId = new ID("b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3");
			public const string CssClassNameFieldName = "CssClassName";
			
					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID ImageFieldId = new ID("c978e4f3-e816-4000-8845-04e6cc2e8609");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID MenuHoverTextFieldId = new ID("13c86a65-f308-438e-bb44-d3ab9c80b0e5");
			public const string MenuHoverTextFieldName = "MenuHoverText";
			
					
			public static readonly ID MenuTitleFieldId = new ID("2f0521a1-2a3f-491d-bc54-7dabac85e6d6");
			public const string MenuTitleFieldName = "MenuTitle";
			
					
			public static readonly ID ShowInMenuFieldId = new ID("64be5630-d2a8-42f4-a127-dd901ee32f6b");
			public const string ShowInMenuFieldName = "ShowInMenu";
			
			

	}

	
	/// <summary>
	/// SiteSection
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/SiteSection</para>	
	/// <para>ID: add81fbd-f1f5-45e0-93a1-26a899526ce4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteSectionConstants.TemplateIdString)]
	public partial class SiteSection  : GlassBase, ISiteSection 
	{
	 public SiteSection(ISitecoreContext context) : base(context)
	    {
	    }

		public SiteSection() : base()
	    {
	    }
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: aca2a76a-21f1-4798-9b69-c87764e9ceee</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The BreadcrumbTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f5de556a-3c9c-4b42-94f3-3ac3a30fa788</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.BreadcrumbTitleFieldName)]
				public virtual string BreadcrumbTitle  {get; set;}
					
						/// <summary>
				/// The CssClassName field.
				/// <para>This will be the Font Awesome Icon classes that will represent the Icons in the breadcrumb</para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b36f38d6-f0e4-413e-8ec9-dc6de5d34bf3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.CssClassNameFieldName)]
				public virtual string CssClassName  {get; set;}
					
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c978e4f3-e816-4000-8845-04e6cc2e8609</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The MenuHoverText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 13c86a65-f308-438e-bb44-d3ab9c80b0e5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.MenuHoverTextFieldName)]
				public virtual string MenuHoverText  {get; set;}
					
						/// <summary>
				/// The MenuTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2f0521a1-2a3f-491d-bc54-7dabac85e6d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.MenuTitleFieldName)]
				public virtual string MenuTitle  {get; set;}
					
						/// <summary>
				/// The ShowInMenu field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 64be5630-d2a8-42f4-a127-dd901ee32f6b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteSectionConstants.ShowInMenuFieldName)]
				public virtual bool ShowInMenu  {get; set;}
					
			
	}
}



namespace Projects.Models.Glass.Common
{


 	/// <summary>
	/// ITaxonomyBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/TaxonomyBase</para>	
	/// <para>ID: b6341215-a5a9-4e2b-b2d8-3939f2af7310</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITaxonomyBaseConstants.TemplateIdString)]
	public partial interface ITaxonomyBase : IGlassBase , global::Projects.Models.Glass.Common.FieldSections.IHasExternalId, global::Projects.Models.Glass.Common.FieldSections.IHasTitle
	{
				}


	public static partial class ITaxonomyBaseConstants{

			public const string TemplateIdString = "b6341215-a5a9-4e2b-b2d8-3939f2af7310";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "TaxonomyBase";

					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
					
			public static readonly ID TitleFieldId = new ID("f3479f8e-7fea-494d-80ab-7ad75ee4d94a");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// TaxonomyBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/TaxonomyBase</para>	
	/// <para>ID: b6341215-a5a9-4e2b-b2d8-3939f2af7310</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITaxonomyBaseConstants.TemplateIdString)]
	public partial class TaxonomyBase  : GlassBase, ITaxonomyBase 
	{
	 public TaxonomyBase(ISitecoreContext context) : base(context)
	    {
	    }

		public TaxonomyBase() : base()
	    {
	    }
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITaxonomyBaseConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f3479f8e-7fea-494d-80ab-7ad75ee4d94a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITaxonomyBaseConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}








namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasExternalId Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasExternalId</para>	
	/// <para>ID: dbed97e8-0520-46d4-bfb8-92c2c7f02754</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasExternalIdConstants.TemplateIdString)]
	public partial interface IHasExternalId : IGlassBase 
	{
								/// <summary>
					/// The ExternalId field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasExternalIdConstants.ExternalIdFieldName)]
					string ExternalId  {get; set;}
			
				}


	public static partial class IHasExternalIdConstants{

			public const string TemplateIdString = "dbed97e8-0520-46d4-bfb8-92c2c7f02754";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasExternalId";

					
			public static readonly ID ExternalIdFieldId = new ID("062112fc-3865-4a6f-8950-d1e26711793b");
			public const string ExternalIdFieldName = "ExternalId";
			
			

	}

	
	/// <summary>
	/// HasExternalId
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasExternalId</para>	
	/// <para>ID: dbed97e8-0520-46d4-bfb8-92c2c7f02754</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasExternalIdConstants.TemplateIdString)]
	public partial class HasExternalId  : GlassBase, IHasExternalId 
	{
	 public HasExternalId(ISitecoreContext context) : base(context)
	    {
	    }

		public HasExternalId() : base()
	    {
	    }
						/// <summary>
				/// The ExternalId field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 062112fc-3865-4a6f-8950-d1e26711793b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasExternalIdConstants.ExternalIdFieldName)]
				public virtual string ExternalId  {get; set;}
					
			
	}
}


namespace Projects.Models.Glass.Common.FieldSections
{


 	/// <summary>
	/// IHasMetadata Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasMetadata</para>	
	/// <para>ID: fb728d23-dcf8-497c-b28e-1f0d91458a35</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasMetadataConstants.TemplateIdString)]
	public partial interface IHasMetadata : IGlassBase 
	{
								/// <summary>
					/// The Keywords field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasMetadataConstants.KeywordsFieldName)]
					string Keywords  {get; set;}
			
								/// <summary>
					/// The MetaDescription field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHasMetadataConstants.MetaDescriptionFieldName)]
					string MetaDescription  {get; set;}
			
				}


	public static partial class IHasMetadataConstants{

			public const string TemplateIdString = "fb728d23-dcf8-497c-b28e-1f0d91458a35";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HasMetadata";

					
			public static readonly ID KeywordsFieldId = new ID("799c85c3-1cb0-40cf-b594-86b438f4192d");
			public const string KeywordsFieldName = "Keywords";
			
					
			public static readonly ID MetaDescriptionFieldId = new ID("1e432dbe-fa95-4b94-b538-bcf52c80c5ba");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
			

	}

	
	/// <summary>
	/// HasMetadata
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Common/FieldSections/HasMetadata</para>	
	/// <para>ID: fb728d23-dcf8-497c-b28e-1f0d91458a35</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHasMetadataConstants.TemplateIdString)]
	public partial class HasMetadata  : GlassBase, IHasMetadata 
	{
	 public HasMetadata(ISitecoreContext context) : base(context)
	    {
	    }

		public HasMetadata() : base()
	    {
	    }
						/// <summary>
				/// The Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 799c85c3-1cb0-40cf-b594-86b438f4192d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasMetadataConstants.KeywordsFieldName)]
				public virtual string Keywords  {get; set;}
					
						/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 1e432dbe-fa95-4b94-b538-bcf52c80c5ba</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHasMetadataConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
			
	}
}
